version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-80}:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: "mongodb://ikagua:aB/987654321@ds119795.mlab.com:19795/ikagia"
      APP_URL: "http://ec2-18-222-72-225.us-east-2.compute.amazonaws.com"
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
